import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState, useEffect, useRef} from 'react'

export default function TypeField(props){

     
      
    return <div>
    <Head>
        <title>Typur - Improve Your Typing Speed</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
    </Head>
    </div>

}